- name: Jira ticket 
  gather_facts: false 
  vars_files: 
   -  vars/jira-vars.yaml
  vars_prompt: 
    - name: token
      prompt: Please ,enter yur token. 
  hosts: localhost
  tasks: 
  - name: create Jira Ticket for db users creation
    community.general.jira:
      uri: '{{ server }}'
      token: '{{ token }}'
      project: '{{ project  }}'
      validate_certs: false
      operation: create
      summary: '{{ title }}'
      description: '{{ description }}'
      issuetype: Task
#    args:
#      fields:
#        customfield_31220: {"value": "OpCos"}
    register: issue
  - name: Show Ticket Number
    debug: 
       msg:  The Ticket Number is  {{ issue.meta.key }}

