apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mongosh
  name: mongosh
  namespace: {{ .Values.clustertypenonprod }}
  {{- with  .Values }}
spec:
  restartPolicy: {{ .restartpolicy }}
  containers:
  - image: {{ .containers.image }}
    name: {{ .containers.name }}
    stdin: {{ .containers.stdin }}
    command:
     - /bin/bash
     - -c
    args: 
     - mongo "$URL" --username $USER -p $PASS  < /tmp/db_commands.js;
    resources:
      limits:
        cpu: {{ .resources.limits.cpu }}
        memory: {{ .resources.limits.memory }}
      requests:
        cpu: {{ .resources.requests.cpu }}
        memory: {{ .resources.requests.memory }}
    envFrom:
    - secretRef:
         name: {{ .namespace_sys.secret.name      }} 
    volumeMounts: 
    - name: script
      mountPath: {{ .configmap.mountPath }}
  volumes:
  - name: script
    configMap: 
      name: {{ .configmap.name }}
      defaultMode: {{ .configmap.defaultMode }}
{{ end }}
